apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-aug29-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag-aug29-1:4080d91f4e60d7bfc798f15dec98d2e8b537c9e2@sha256:cdb49ddfbf939fd81ee2b86537987fd3f178a7bed4bca6b83852ad7c310242e6 # use pre-built to bootstrap 
          name: app-inference
